language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="33ca531d-f9cb-44ce-9bd2-135733da5612"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - BakhmutskyAN@mpei.ru
    on_success: never # default: change
    on_failure: always # default: always