language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="7b8e0b33-c86e-4149-8d05-c2fe6f634094"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - BakhmutskyAN@mpei.ru
    on_success: never # default: change
    on_failure: always # default: always